apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bluecompute-web
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /oauth/token
        backend:
          serviceName: auth-service
          servicePort: 8080
      - path: /
        backend:
          serviceName: bluecompute-web
          servicePort: 80
